
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GNU GPLv3"
[[mods]]
modId="bathappypro"

version="0.1-Forge+1.20.1"

displayName="Bat Happy Pro"

authors="Cu6"

description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"